import '../core/constants/schooldesk_glossary.dart';
import '../services/feature_availability_service.dart';

class SchoolDeskScreenMetadata {
  final String route;
  final String title;
  final String module;
  final String portal;
  final bool isPublic;
  final bool isShared;
  final SchoolDeskFeature? feature;

  const SchoolDeskScreenMetadata({
    required this.route,
    required this.title,
    required this.module,
    required this.portal,
    this.isPublic = false,
    this.isShared = false,
    this.feature,
  });

  String get semanticLabel {
    final portalLabel = portal[0].toUpperCase() + portal.substring(1);
    return '$portalLabel portal, $module, $title';
  }
}

class SchoolDeskScreenRegistry {
  SchoolDeskScreenRegistry._();

  static const List<SchoolDeskScreenMetadata> all = [
    SchoolDeskScreenMetadata(
      route: '/',
      title: 'Landing',
      module: 'Public Access',
      portal: 'public',
      isPublic: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/landing-page-screen',
      title: 'Landing',
      module: 'Public Access',
      portal: 'public',
      isPublic: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/onboarding-screen',
      title: 'Sign In',
      module: 'Authentication',
      portal: 'public',
      isPublic: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-login-screen',
      title: 'Principal Sign In',
      module: 'Authentication',
      portal: 'public',
      isPublic: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-login-screen',
      title: 'Admin Sign In',
      module: 'Authentication',
      portal: 'public',
      isPublic: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-login-screen',
      title: 'Teacher Sign In',
      module: 'Authentication',
      portal: 'public',
      isPublic: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-login-screen',
      title: 'Parent Sign In',
      module: 'Authentication',
      portal: 'public',
      isPublic: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-dashboard-screen',
      title: 'Principal Dashboard',
      module: 'Overview',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-school-profile-screen',
      title: SchoolDeskGlossary.schoolProfile,
      module: 'Governance',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-user-management-screen',
      title: SchoolDeskGlossary.accessPermissions,
      module: 'Governance',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-user-management-screen/create',
      title: 'Create Account',
      module: 'Governance',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-user-management-screen/edit',
      title: 'Edit Account',
      module: 'Governance',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-user-management-screen/assign-children',
      title: 'Assign Children',
      module: 'Governance',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/staff-management-screen',
      title: SchoolDeskGlossary.staffOversight,
      module: 'People',
      portal: 'principal',
      feature: SchoolDeskFeature.adminStaff,
    ),
    SchoolDeskScreenMetadata(
      route: '/staff-management-screen/form',
      title: 'Staff Form',
      module: 'People',
      portal: 'shared',
      isShared: true,
      feature: SchoolDeskFeature.adminStaff,
    ),
    SchoolDeskScreenMetadata(
      route: '/student-oversight-screen',
      title: SchoolDeskGlossary.studentOversight,
      module: 'Students',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/approval-center-screen',
      title: SchoolDeskGlossary.approvalCenter,
      module: 'Approvals',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/fee-monitoring-screen',
      title: SchoolDeskGlossary.feeMonitoring,
      module: 'Finance',
      portal: 'principal',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/timetable-management-screen',
      title: SchoolDeskGlossary.timetableRecords,
      module: 'Academics',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/syllabus-monitoring-screen',
      title: SchoolDeskGlossary.syllabusRecords,
      module: 'Academics',
      portal: 'principal',
      feature: SchoolDeskFeature.syllabusRecords,
    ),
    SchoolDeskScreenMetadata(
      route: '/exams-results-screen',
      title: SchoolDeskGlossary.examRecords,
      module: 'Academics',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/communication-center-screen',
      title: SchoolDeskGlossary.communicationCenter,
      module: 'Communication',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/complaint-management-screen',
      title: SchoolDeskGlossary.complaints,
      module: 'Communication',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/events-calendar-screen',
      title: SchoolDeskGlossary.calendar,
      module: SchoolDeskGlossary.calendar,
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/reports-analytics-screen',
      title: SchoolDeskGlossary.reports,
      module: SchoolDeskGlossary.reports,
      portal: 'principal',
      feature: SchoolDeskFeature.reportsExports,
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-academic-info-screen',
      title: SchoolDeskGlossary.academicRecords,
      module: 'School Info',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-analytics-screen',
      title: SchoolDeskGlossary.analytics,
      module: SchoolDeskGlossary.reports,
      portal: 'principal',
      feature: SchoolDeskFeature.principalAnalytics,
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-dashboard-screen',
      title: 'Admin Dashboard',
      module: 'Overview',
      portal: 'admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-students-screen',
      title: SchoolDeskGlossary.students,
      module: 'Students',
      portal: 'admin',
      feature: SchoolDeskFeature.adminStudents,
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-teachers-screen',
      title: SchoolDeskGlossary.staff,
      module: 'People',
      portal: 'admin',
      feature: SchoolDeskFeature.adminStaff,
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-attendance-screen',
      title: SchoolDeskGlossary.attendance,
      module: SchoolDeskGlossary.attendance,
      portal: 'admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-fees-screen',
      title: SchoolDeskGlossary.fees,
      module: 'Finance',
      portal: 'admin',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-fees-screen/structures/form',
      title: 'Fee Structure Form',
      module: 'Finance',
      portal: 'admin',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-fees-screen/invoices/generate',
      title: 'Generate Invoices',
      module: 'Finance',
      portal: 'admin',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-fees-screen/payments/record',
      title: 'Record Payment',
      module: 'Finance',
      portal: 'admin',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-fees-screen/payment-requests',
      title: 'Payment Requests',
      module: 'Finance',
      portal: 'admin',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-fees-screen/payment-requests/decision',
      title: 'Review Payment',
      module: 'Finance',
      portal: 'admin',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-timetable-screen',
      title: SchoolDeskGlossary.timetable,
      module: 'Academics',
      portal: 'admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-timetable-screen/generate',
      title: 'Generate Timetable',
      module: 'Academics',
      portal: 'admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-timetable-screen/period',
      title: 'Timetable Period Form',
      module: 'Academics',
      portal: 'admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-timetable-screen/substitution',
      title: 'Substitution Form',
      module: 'Academics',
      portal: 'admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-exams-screen',
      title: SchoolDeskGlossary.exams,
      module: 'Academics',
      portal: 'admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-exams-screen/form',
      title: 'Exam Form',
      module: 'Academics',
      portal: 'admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-exams-screen/schedule',
      title: 'Exam Schedule Form',
      module: 'Academics',
      portal: 'admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-communication-screen',
      title: SchoolDeskGlossary.communication,
      module: SchoolDeskGlossary.communication,
      portal: 'admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-helpdesk-screen',
      title: SchoolDeskGlossary.helpdesk,
      module: SchoolDeskGlossary.communication,
      portal: 'admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-documents-screen',
      title: SchoolDeskGlossary.documents,
      module: 'Records',
      portal: 'admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-user-access-screen',
      title: SchoolDeskGlossary.access,
      module: SchoolDeskGlossary.access,
      portal: 'admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-user-access-screen/create',
      title: 'Create Account',
      module: SchoolDeskGlossary.access,
      portal: 'admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-user-access-screen/edit',
      title: 'Edit Account',
      module: SchoolDeskGlossary.access,
      portal: 'admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-user-access-screen/assign-children',
      title: 'Assign Children',
      module: SchoolDeskGlossary.access,
      portal: 'admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-reports-screen',
      title: SchoolDeskGlossary.reports,
      module: SchoolDeskGlossary.reports,
      portal: 'admin',
      feature: SchoolDeskFeature.reportsExports,
    ),
    SchoolDeskScreenMetadata(
      route: '/admin-academic-info-screen',
      title: 'Academic Info',
      module: 'School Info',
      portal: 'admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/academic-management-screen',
      title: SchoolDeskGlossary.academicManagement,
      module: 'Academics',
      portal: 'shared',
      isShared: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/academic-management-screen/year',
      title: 'Academic Year Form',
      module: 'Academics',
      portal: 'shared',
      isShared: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/academic-management-screen/subject',
      title: 'Subject Form',
      module: 'Academics',
      portal: 'shared',
      isShared: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/academic-management-screen/class',
      title: 'Class Form',
      module: 'Academics',
      portal: 'shared',
      isShared: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/academic-management-screen/curriculum',
      title: 'Curriculum Form',
      module: 'Academics',
      portal: 'shared',
      isShared: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/id-card-generation-screen',
      title: SchoolDeskGlossary.idCards,
      module: 'School Info',
      portal: 'admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/report-card-generator-screen',
      title: 'Report Card Generator',
      module: 'Reports',
      portal: 'admin',
      feature: SchoolDeskFeature.reportsExports,
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-dashboard-screen',
      title: 'Teacher Dashboard',
      module: 'Overview',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-classes-screen',
      title: 'My Classes',
      module: 'Classroom',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-attendance-screen',
      title: 'Attendance',
      module: 'Classroom',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-homework-screen',
      title: 'Homework',
      module: 'Classroom',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-homework-screen/form',
      title: 'Homework Form',
      module: 'Classroom',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-homework-screen/submissions',
      title: 'Homework Submissions',
      module: 'Classroom',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-lesson-planner-screen',
      title: 'Lesson Planner',
      module: 'Academics',
      portal: 'teacher',
      feature: SchoolDeskFeature.teacherLessonPlanner,
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-performance-screen',
      title: 'Student Performance',
      module: 'Academics',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-student-notes-screen',
      title: 'Student Notes',
      module: 'Academics',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-resources-screen',
      title: 'Resources',
      module: 'Academics',
      portal: 'teacher',
      feature: SchoolDeskFeature.teacherResources,
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-communication-screen',
      title: 'Communication',
      module: 'Communication',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-parent-interaction-screen',
      title: 'Parent Interaction',
      module: 'Communication',
      portal: 'teacher',
      feature: SchoolDeskFeature.teacherParentMeetings,
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-leave-screen',
      title: 'Leave',
      module: 'Management',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-leave-screen/request',
      title: 'Apply Leave',
      module: 'Management',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-discipline-screen',
      title: 'Discipline & Incidents',
      module: 'Management',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-reports-screen',
      title: 'Reports',
      module: 'Reports',
      portal: 'teacher',
      feature: SchoolDeskFeature.reportsExports,
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-diary-screen',
      title: 'Class Diary',
      module: 'Classroom',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-academic-info-screen',
      title: 'Academic Info',
      module: 'School Info',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-dashboard-screen',
      title: 'Parent Dashboard',
      module: 'Overview',
      portal: 'parent',
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-academic-progress-screen',
      title: 'Academic Progress',
      module: 'Child Academics',
      portal: 'parent',
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-attendance-screen',
      title: 'Attendance',
      module: 'Child Academics',
      portal: 'parent',
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-homework-screen',
      title: 'Homework',
      module: 'Child Academics',
      portal: 'parent',
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-homework-screen/submit',
      title: 'Submit Homework',
      module: 'Child Academics',
      portal: 'parent',
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-diary-screen',
      title: 'Class Diary',
      module: 'Child Academics',
      portal: 'parent',
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-notices-screen',
      title: 'School Notices',
      module: 'Communication',
      portal: 'parent',
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-teacher-chat-screen',
      title: 'Teacher Chat & PTM',
      module: 'Communication',
      portal: 'parent',
      feature: SchoolDeskFeature.teacherParentMeetings,
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-fees-screen',
      title: SchoolDeskGlossary.fees,
      module: 'Finance',
      portal: 'parent',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-fees-screen/payment',
      title: 'Submit Payment Request',
      module: 'Finance',
      portal: 'parent',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/fee-payment-receipt-screen',
      title: 'Payments & Receipts',
      module: 'Finance',
      portal: 'parent',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-leave-screen',
      title: 'Leave Requests',
      module: 'Finance & Admin',
      portal: 'parent',
      feature: SchoolDeskFeature.parentStudentLeave,
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-leave-screen/request',
      title: 'Submit Leave Request',
      module: 'Finance & Admin',
      portal: 'parent',
      feature: SchoolDeskFeature.parentStudentLeave,
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-calendar-screen',
      title: SchoolDeskGlossary.calendar,
      module: 'School',
      portal: 'parent',
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-documents-screen',
      title: SchoolDeskGlossary.documents,
      module: 'School',
      portal: 'parent',
      feature: SchoolDeskFeature.documents,
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-academic-info-screen',
      title: 'Academic Info',
      module: 'School Info',
      portal: 'parent',
    ),
    SchoolDeskScreenMetadata(
      route: '/notification-center-screen',
      title: 'Notifications',
      module: 'Shared Tools',
      portal: 'shared',
      isShared: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/settings-screen',
      title: 'Settings',
      module: 'Shared Tools',
      portal: 'shared',
      isShared: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/profile-screen',
      title: 'Profile',
      module: 'Shared Tools',
      portal: 'shared',
      isShared: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/global-search-screen',
      title: 'Global Search',
      module: 'Shared Tools',
      portal: 'shared',
      isShared: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/homework-messaging-screen',
      title: 'Homework Messaging',
      module: 'Shared Tools',
      portal: 'shared',
      isShared: true,
    ),
  ];

  static final Map<String, SchoolDeskScreenMetadata> _byRoute = {
    for (final screen in all) screen.route: screen,
  };

  static SchoolDeskScreenMetadata? byRoute(String route) {
    return _byRoute[route];
  }
}
