import 'package:schooldesk1/core/constants/schooldesk_glossary.dart';
import 'package:schooldesk1/core/services/feature_availability_service.dart';

class SchoolDeskScreenMetadata {
  final String route;
  final String title;
  final String module;
  final String portal;
  final bool isPublic;
  final bool isShared;
  final SchoolDeskFeature? feature;

  const SchoolDeskScreenMetadata({
    required this.route,
    required this.title,
    required this.module,
    required this.portal,
    this.isPublic = false,
    this.isShared = false,
    this.feature,
  });

  String get semanticLabel {
    final portalLabel = portal[0].toUpperCase() + portal.substring(1);
    return '$portalLabel portal, $module, $title';
  }
}

class SchoolDeskScreenRegistry {
  SchoolDeskScreenRegistry._();

  static const List<SchoolDeskScreenMetadata> all = [
    SchoolDeskScreenMetadata(
      route: '/',
      title: 'Landing',
      module: 'Public Access',
      portal: 'public',
      isPublic: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/landing-page-screen',
      title: 'Landing',
      module: 'Public Access',
      portal: 'public',
      isPublic: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/onboarding-screen',
      title: 'Sign In',
      module: 'Authentication',
      portal: 'public',
      isPublic: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-login-screen',
      title: 'Principal Sign In',
      module: 'Authentication',
      portal: 'public',
      isPublic: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-login-screen',
      title: 'Teacher Sign In',
      module: 'Authentication',
      portal: 'public',
      isPublic: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-login-screen',
      title: 'Parent Sign In',
      module: 'Authentication',
      portal: 'public',
      isPublic: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/kiosk-login-screen',
      title: 'Kiosk Sign In',
      module: 'Authentication',
      portal: 'public',
      isPublic: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/kiosk-qr-attendance-screen',
      title: 'QR Attendance Kiosk',
      module: SchoolDeskGlossary.attendance,
      portal: 'kiosk',
    ),
    SchoolDeskScreenMetadata(
      route: '/super-admin-dashboard-screen',
      title: 'Super Admin Dashboard',
      module: 'System Administration',
      portal: 'super_admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/super-admin-audit-logs-screen',
      title: 'Audit Logs',
      module: 'System Administration',
      portal: 'super_admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/super-admin-system-monitor-screen',
      title: 'System Monitor',
      module: 'System Administration',
      portal: 'super_admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/super-admin-access-screen',
      title: 'Access & Permissions',
      module: 'School Management',
      portal: 'super_admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/super-admin-issues-screen',
      title: 'Issues',
      module: 'System Administration',
      portal: 'super_admin',
    ),
    SchoolDeskScreenMetadata(
      route: '/help-screen',
      title: 'Help & Tutorials',
      module: 'General Support',
      portal: 'shared',
      isShared: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-dashboard-screen',
      title: 'Principal Dashboard',
      module: 'Overview',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/coordinator-dashboard-screen',
      title: 'Coordinator Dashboard',
      module: 'Overview',
      portal: 'coordinator',
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-school-profile-screen',
      title: SchoolDeskGlossary.schoolProfile,
      module: 'Governance',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-user-management-screen',
      title: SchoolDeskGlossary.accessPermissions,
      module: 'Governance',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/system-monitor-screen',
      title: 'System Monitor',
      module: 'Operations',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/guardian-directory-screen',
      title: 'Parents',
      module: 'People',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-classes-screen',
      title: 'Class Hub',
      module: 'Academics',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-attendance-screen',
      title: SchoolDeskGlossary.attendance,
      module: SchoolDeskGlossary.attendance,
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-subjects-screen',
      title: 'Subjects',
      module: 'Academics',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-timetable-screen',
      title: 'Timetable',
      module: 'Academics',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-lesson-planner-screen',
      title: 'Lesson Planners',
      module: 'Academics',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-user-management-screen/create',
      title: 'Create Account',
      module: 'Governance',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-user-management-screen/edit',
      title: 'Edit Account',
      module: 'Governance',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-user-management-screen/assign-children',
      title: 'Assign Children',
      module: 'Governance',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/staff-management-screen',
      title: SchoolDeskGlossary.staffOversight,
      module: 'People',
      portal: 'principal',
      feature: SchoolDeskFeature.adminStaff,
    ),
    SchoolDeskScreenMetadata(
      route: '/staff-management-screen/form',
      title: 'Staff Form',
      module: 'People',
      portal: 'shared',
      isShared: true,
      feature: SchoolDeskFeature.adminStaff,
    ),
    SchoolDeskScreenMetadata(
      route: '/student-oversight-screen',
      title: SchoolDeskGlossary.studentOversight,
      module: 'Students',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/approval-center-screen',
      title: SchoolDeskGlossary.approvalCenter,
      module: 'Approvals',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/fee-monitoring-screen',
      title: SchoolDeskGlossary.feeMonitoring,
      module: 'Finance',
      portal: 'principal',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-fees-screen/payment-requests',
      title: 'Payment Requests',
      module: 'Finance',
      portal: 'principal',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-fees-screen/payment-request-decision',
      title: 'Payment Request Decision',
      module: 'Finance',
      portal: 'principal',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-fees-screen/fee-structure',
      title: 'Fee Structure Form',
      module: 'Finance',
      portal: 'principal',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-fees-screen/payment-record',
      title: 'Offline Payment',
      module: 'Finance',
      portal: 'principal',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/principal/fees',
      title: 'Fee Operations',
      module: 'Finance',
      portal: 'principal',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/principal/fee-concessions',
      title: 'Fee Concessions',
      module: 'Finance',
      portal: 'principal',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/principal/payment-requests',
      title: 'Review Payment Proofs',
      module: 'Finance',
      portal: 'principal',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/principal/fee-structures',
      title: 'Fee Structures',
      module: 'Finance',
      portal: 'principal',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/principal/collect-fee',
      title: 'Record Payment',
      module: 'Finance',
      portal: 'principal',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/principal/payment-config',
      title: 'Payment Configuration',
      module: 'Finance',
      portal: 'principal',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/communication-center-screen',
      title: 'Communications',
      module: 'Communication',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-chat-communications-screen',
      title: 'Messages',
      module: 'Communication',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/complaint-management-screen',
      title: SchoolDeskGlossary.complaints,
      module: 'Communication',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/events-calendar-screen',
      title: SchoolDeskGlossary.calendar,
      module: 'Academic Calendar',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/reports-analytics-screen',
      title: SchoolDeskGlossary.reports,
      module: SchoolDeskGlossary.reports,
      portal: 'principal',
      feature: SchoolDeskFeature.reportsExports,
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-academic-info-screen',
      title: SchoolDeskGlossary.academicRecords,
      module: 'School Info',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-analytics-screen',
      title: SchoolDeskGlossary.analytics,
      module: SchoolDeskGlossary.reports,
      portal: 'principal',
      feature: SchoolDeskFeature.principalAnalytics,
    ),
    SchoolDeskScreenMetadata(
      route: '/academic-management-screen',
      title: 'Academic Years',
      module: 'Academics',
      portal: 'shared',
      isShared: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/academic-management-screen/year/detail',
      title: 'Academic Year Detail',
      module: 'Academics',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/academic-management-screen/year/classwise-export',
      title: 'Classwise Export',
      module: 'Academics',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/academic-management-screen/year/users-export',
      title: 'Users-wise Export',
      module: 'Academics',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/academic-management-screen/year/fees-export',
      title: 'Fees Export',
      module: 'Academics',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/academic-management-screen/year',
      title: 'Academic Year Form',
      module: 'Academics',
      portal: 'shared',
      isShared: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/academic-management-screen/subject',
      title: 'Subject Form',
      module: 'Academics',
      portal: 'shared',
      isShared: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/academic-management-screen/class',
      title: 'Class Form',
      module: 'Academics',
      portal: 'shared',
      isShared: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/academic-management-screen/curriculum',
      title: 'Curriculum Form',
      module: 'Academics',
      portal: 'shared',
      isShared: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/id-card-generation-screen',
      title: SchoolDeskGlossary.idCards,
      module: 'School Info',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-dashboard-screen',
      title: 'Teacher Dashboard',
      module: 'Overview',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-classes-screen',
      title: 'My Classes',
      module: 'Classroom',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-timetable-screen',
      title: 'Teacher Timetable',
      module: 'Classroom',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-calendar-screen',
      title: 'Academic Calendar',
      module: 'School',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-attendance-screen',
      title: 'Student Attendance',
      module: 'Classroom',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-attendance-history-screen',
      title: 'Attendance History',
      module: 'Classroom',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-my-attendance-screen',
      title: 'My Attendance',
      module: 'Today',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-documents-screen',
      title: SchoolDeskGlossary.documents,
      module: 'Classroom',
      portal: 'teacher',
      feature: SchoolDeskFeature.documents,
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-communication-screen',
      title: 'Communication',
      module: 'Communication',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-parent-interaction-screen',
      title: 'Parent Interaction',
      module: 'Communication',
      portal: 'teacher',
      feature: SchoolDeskFeature.teacherParentMeetings,
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-leave-screen',
      title: 'Leave',
      module: 'Management',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-leave-screen/request',
      title: 'Apply Leave',
      module: 'Management',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-homework-screen',
      title: 'Homework',
      module: 'Classroom',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-homework-screen/form',
      title: 'Post Homework',
      module: 'Classroom',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-homework-screen/submissions',
      title: 'Homework Feedback',
      module: 'Classroom',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-complaints-screen',
      title: 'Complaints',
      module: 'Communication',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-dashboard-screen',
      title: 'Parent Dashboard',
      module: 'Overview',
      portal: 'parent',
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-attendance-screen',
      title: 'Attendance',
      module: 'Child Academics',
      portal: 'parent',
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-homework-screen',
      title: 'Homework',
      module: 'Child Academics',
      portal: 'parent',
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-homework-screen/submit',
      title: 'Submit Homework',
      module: 'Child Academics',
      portal: 'parent',
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-lesson-planner-screen',
      title: 'Lesson Planner',
      module: 'Child Academics',
      portal: 'parent',
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-health-screen',
      title: 'Health Updates',
      module: 'Child Health',
      portal: 'parent',
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-teacher-chat-screen',
      title: 'Teacher Chat & PTM',
      module: 'Communication',
      portal: 'parent',
      feature: SchoolDeskFeature.teacherParentMeetings,
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-fees-screen',
      title: SchoolDeskGlossary.fees,
      module: 'Finance',
      portal: 'parent',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-fees-screen/payment',
      title: 'Submit Payment Request',
      module: 'Finance',
      portal: 'parent',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-fees-screen/payment-selection',
      title: 'Select Payment',
      module: 'Finance',
      portal: 'parent',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-fees-screen/payment-processing',
      title: 'Payment Processing',
      module: 'Finance',
      portal: 'parent',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/parent/fees',
      title: 'My Fees',
      module: 'Finance',
      portal: 'parent',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/parent/payment-flow',
      title: 'Pay Fee',
      module: 'Finance',
      portal: 'parent',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/parent/payment-history',
      title: 'Payment History',
      module: 'Finance',
      portal: 'parent',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/parent/receipt',
      title: 'Receipt',
      module: 'Finance',
      portal: 'parent',
      feature: SchoolDeskFeature.adminFees,
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-leave-screen',
      title: 'Leave Requests',
      module: 'Student Support',
      portal: 'parent',
      feature: SchoolDeskFeature.parentStudentLeave,
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-leave-screen/request',
      title: 'Submit Leave Request',
      module: 'Student Support',
      portal: 'parent',
      feature: SchoolDeskFeature.parentStudentLeave,
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-calendar-screen',
      title: 'Academic Calendar',
      module: 'School',
      portal: 'parent',
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-documents-screen',
      title: SchoolDeskGlossary.documents,
      module: 'School',
      portal: 'parent',
      feature: SchoolDeskFeature.documents,
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-timetable-screen',
      title: 'Timetable',
      module: 'Child Academics',
      portal: 'parent',
    ),

    SchoolDeskScreenMetadata(
      route: '/parent-ptm-booking-screen',
      title: 'PTM Booking',
      module: 'Communication',
      portal: 'parent',
      feature: SchoolDeskFeature.teacherParentMeetings,
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-event-posts-screen',
      title: 'Event Posts',
      module: 'Classroom',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/teacher-lesson-planner-screen',
      title: 'Lesson Planner',
      module: 'Academics',
      portal: 'teacher',
    ),
    SchoolDeskScreenMetadata(
      route: '/school-gallery-screen',
      title: 'School Gallery',
      module: 'Shared Tools',
      portal: 'shared',
      isShared: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-event-approvals-screen',
      title: 'School Posts Approval',
      module: 'Communication',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-event-posts-screen',
      title: 'School Feed Posts',
      module: 'Communication',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-documents-screen',
      title: SchoolDeskGlossary.documents,
      module: 'Records',
      portal: 'principal',
      feature: SchoolDeskFeature.documents,
    ),
    SchoolDeskScreenMetadata(
      route: '/principal-audit-logs-screen',
      title: 'Audit Logs',
      module: 'Records',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/notification-center-screen',
      title: 'Notifications',
      module: 'Shared Tools',
      portal: 'shared',
      isShared: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/settings-screen',
      title: 'Settings',
      module: 'Shared Tools',
      portal: 'shared',
      isShared: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/profile-screen',
      title: 'Profile',
      module: 'Shared Tools',
      portal: 'shared',
      isShared: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/global-search-screen',
      title: 'Global Search',
      module: 'Shared Tools',
      portal: 'shared',
      isShared: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/homework-messaging-screen',
      title: 'Homework Messaging',
      module: 'Shared Tools',
      portal: 'shared',
      isShared: true,
    ),
    SchoolDeskScreenMetadata(
      route: '/login-loading-screen',
      title: 'Loading',
      module: 'System',
      portal: 'shared',
    ),
    SchoolDeskScreenMetadata(
      route: '/fee-home-screen',
      title: 'Fees',
      module: 'Finance',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/fee-structures-screen',
      title: 'Fee Structures',
      module: 'Finance',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/fee-collect-screen',
      title: 'Collect Fees',
      module: 'Finance',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/fee-ledger-screen',
      title: 'Fee Ledger',
      module: 'Finance',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/fee-payment-config-screen',
      title: 'Payment Settings',
      module: 'Finance',
      portal: 'principal',
    ),
    SchoolDeskScreenMetadata(
      route: '/parent-complaints-screen',
      title: 'Complaints',
      module: 'Communication',
      portal: 'parent',
    ),
  ];

  static final Map<String, SchoolDeskScreenMetadata> _byRoute = {
    for (final screen in all) screen.route: screen,
  };

  static SchoolDeskScreenMetadata? byRoute(String route) {
    return _byRoute[route];
  }
}
