"use client";

import { useEffect, useMemo, useState } from "react";
import { Search, MessageSquareMore } from "@/lib/lucide-react";
import type { Row } from "./types";
import { api, formatDateTime, stringValue } from "./utils";

export function AdmissionInquiriesWorkspace() {
  const [rows, setRows] = useState<Row[]>([]); const [selected, setSelected] = useState<Row | null>(null); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { void api("admission-inquiries").then((data) => { const list = Array.isArray(data) ? data as Row[] : []; setRows(list); setSelected(list[0] ?? null); }).catch((e) => setError(e instanceof Error ? e.message : "Unable to load admission inquiries")).finally(() => setLoading(false)); }, []);
  const visible = useMemo(() => rows.filter((row) => Object.values(row).join(" ").toLowerCase().includes(query.trim().toLowerCase())), [rows, query]);
  return <section className="ops-module"><div className="ops-module-heading"><div><div className="ops-module-icon green"><MessageSquareMore size={20}/></div><div><p className="ops-kicker">Admissions</p><h2>Admission Inquiries</h2><p>Every enquiry submitted through the public website, available to school leadership.</p></div></div></div>{error && <p className="ops-inline-error">{error}</p>}<div className="ops-inquiry-toolbar"><label className="search-input"><Search size={16}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search parent, child, phone, or program"/></label><span>{visible.length} inquiry{visible.length === 1 ? "" : "ies"}</span></div>{loading ? <div className="skeleton-container"><div className="skeleton skeleton-row"/><div className="skeleton skeleton-row"/></div> : <div className="ops-inquiry-layout"><div className="ops-inquiry-list">{visible.length ? visible.map((row) => <button type="button" key={stringValue(row.id)} className={selected?.id === row.id ? "active" : ""} onClick={() => setSelected(row)}><b>{stringValue(row.parent_name)}</b><span>{stringValue(row.program)} · {stringValue(row.child_age)}</span><small>{formatDateTime(row.submitted_at)}</small></button>) : <p className="ops-empty-small">No admission inquiries found.</p>}</div>{selected && <article className="ops-inquiry-detail"><h3>{stringValue(selected.parent_name)}</h3><small>Submitted {formatDateTime(selected.submitted_at)}</small><dl><dt>Phone</dt><dd>{stringValue(selected.phone)}</dd><dt>Email</dt><dd>{stringValue(selected.email)}</dd><dt>Child</dt><dd>{stringValue(selected.child_name) || "Not provided"}</dd><dt>Age</dt><dd>{stringValue(selected.child_age)}</dd><dt>Program</dt><dd>{stringValue(selected.program)}</dd><dt>Message</dt><dd>{stringValue(selected.message) || "No message provided."}</dd></dl></article>}</div>}</section>;
}
