#!/usr/bin/env bash

# Run Flutter on a wireless Android device while retaining the complete
# Flutter, Android logcat, and local Edge Function streams for later review.
#
# The local env file intentionally points at 127.0.0.1:54321. On a physical
# device that address would mean the phone, so this script installs an ADB
# reverse tunnel from the phone's localhost to the host's Docker Supabase
# gateway before starting Flutter.
set -euo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
requested_device="${1:-}"
env_file_arg="${2:-env.local.json}"
if [[ "$env_file_arg" = /* ]]; then
  env_file="$env_file_arg"
else
  env_file="$root_dir/$env_file_arg"
fi

cd "$root_dir"

if [[ ! -f "$env_file" ]]; then
  echo "Flutter env file is not available: $env_file" >&2
  exit 1
fi

device_is_ready() {
  [[ -n "${1:-}" ]] && adb -s "$1" get-state 2>/dev/null | grep -qx device
}

connected_devices() {
  adb devices | awk '$2 == "device" {print $1}'
}

device="$requested_device"
if [[ -n "$device" ]] && ! device_is_ready "$device"; then
  # This helps when the user has an IP:port from an earlier wireless-debug
  # session and Android has since rotated to an mDNS TLS serial.
  adb connect "$device" >/dev/null 2>&1 || true
fi

if ! device_is_ready "$device"; then
  mapfile -t available_devices < <(connected_devices)
  if [[ "${#available_devices[@]}" -eq 1 ]]; then
    device="${available_devices[0]}"
    if [[ -n "$requested_device" ]]; then
      echo "Requested device unavailable; using the only connected device: $device"
    fi
  else
    echo "Android device is not available: ${requested_device:-<auto-detect>}" >&2
    echo "Connected devices:" >&2
    adb devices -l >&2 || true
    echo "Connect wireless debugging first, then retry." >&2
    exit 1
  fi
fi

api_base_url="$(jq -er '.API_BASE_URL' "$env_file")"
case "$api_base_url" in
  http://127.0.0.1:*/* | http://localhost:*/*) ;;
  *)
    echo "Refusing to run wireless local QA with non-local API_BASE_URL: $api_base_url" >&2
    echo "Use env.local.json generated by scripts/local_supabase.sh." >&2
    exit 1
    ;;
esac

health_url="${api_base_url%/}/health"
health_status="$(curl --silent --output /dev/null --write-out '%{http_code}' \
  --max-time 5 "$health_url" || true)"
if [[ "$health_status" != "200" ]]; then
  echo "Local Docker API is not ready; starting the repository-local Supabase stack..."
  scripts/local_supabase.sh start
  health_status="$(curl --silent --output /dev/null --write-out '%{http_code}' \
    --max-time 5 "$health_url" || true)"
fi
if [[ "$health_status" != "200" ]]; then
  echo "Local Docker API health check failed: $health_url (HTTP $health_status)" >&2
  echo "Run scripts/local_supabase.sh functions in another terminal if the Edge API is not serving." >&2
  exit 1
fi

# Keep the app's local URLs unchanged and route the phone's localhost back to
# the host. This covers the API, Auth, Storage, and Realtime gateway on 54321.
adb -s "$device" reverse tcp:54321 tcp:54321 >/dev/null

stamp="$(date +%Y%m%d-%H%M%S)"
log_dir="${FLUTTER_LOG_DIR:-$root_dir/test-artifacts/flutter-logs/$stamp}"
mkdir -p "$log_dir"

cat >"$log_dir/run-meta.txt" <<EOF
started_at=$(date --iso-8601=seconds)
device=$device
env_file=$env_file
api_base_url=$api_base_url
local_health_url=$health_url
local_health_status=$health_status
adb_reverse=54321->54321
working_directory=$root_dir
EOF

logcat_pid=""
edge_pid=""
cleanup() {
  if [[ -n "$logcat_pid" ]]; then
    kill "$logcat_pid" 2>/dev/null || true
  fi
  if [[ -n "$edge_pid" ]]; then
    kill "$edge_pid" 2>/dev/null || true
  fi
}
trap cleanup EXIT INT TERM

adb -s "$device" logcat -v threadtime >"$log_dir/android-logcat.log" 2>&1 &
logcat_pid=$!

edge_container="supabase_edge_runtime_schooldesk-local"
if docker ps --format '{{.Names}}' | rg -qx "$edge_container"; then
  docker logs -f --since 1s "$edge_container" >"$log_dir/edge-runtime.log" 2>&1 &
  edge_pid=$!
else
  echo "Local Edge container is not running: $edge_container" \
    >"$log_dir/edge-runtime.log"
fi

echo "Capturing Flutter run logs in: $log_dir"
echo "Flutter: $log_dir/flutter-run.log"
echo "Android: $log_dir/android-logcat.log"
echo "Edge:    $log_dir/edge-runtime.log"

set +e
flutter run \
  -d "$device" \
  --dart-define-from-file="$env_file" \
  2>&1 | tee "$log_dir/flutter-run.log"
flutter_status=${PIPESTATUS[0]}
set -e

printf 'finished_at=%s\nflutter_exit=%s\n' \
  "$(date --iso-8601=seconds)" "$flutter_status" >>"$log_dir/run-meta.txt"
exit "$flutter_status"
