#!/usr/bin/env bash
set -euo pipefail

# Read-only role smoke against the synthetic local Supabase stack.
# Credentials are generated by scripts/local_supabase.sh prepare and are never
# printed. This checks the real Edge API paths used by the Flutter client.

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

command -v curl >/dev/null || { echo "curl is required" >&2; exit 1; }
command -v jq >/dev/null || { echo "jq is required" >&2; exit 1; }
test -f env.local.json || {
  echo "env.local.json is missing; run scripts/local_supabase.sh prepare" >&2
  exit 1
}

api_base="$(jq -er '.API_BASE_URL' env.local.json)"
school_id="00000000-0000-4000-8000-000000000001"

login() {
  local username_key="$1"
  local password_key="$2"
  local username password client_ip
  username="$(jq -er ".${username_key}" env.local.json)"
  password="$(jq -er ".${password_key}" env.local.json)"
  # Keep each synthetic role outside the shared loopback login bucket. The
  # dedicated security smoke intentionally uses one IP to verify 429 behavior.
  client_ip="198.18.$((RANDOM % 254)).$((RANDOM % 254))"
  curl -fsS --max-time 15 \
    -X POST "$api_base/auth/login" \
    -H 'Content-Type: application/json' \
    -H "x-forwarded-for: $client_ip" \
    --data "$(jq -nc \
      --arg username "$username" \
      --arg password "$password" \
      --arg school_id "$school_id" \
      '{username:$username,password:$password,school_id:$school_id}')"
}

status() {
  local token="$1"
  local path="$2"
  curl -fsS --max-time 15 -o /dev/null -w '%{http_code}' \
    "$api_base$path" -H "Authorization: Bearer $token"
}

for spec in \
  "principal:QA_PRINCIPAL_USERNAME:QA_PRINCIPAL_PASSWORD" \
  "admin:QA_ADMIN_USERNAME:QA_ADMIN_PASSWORD" \
  "coordinator:QA_COORDINATOR_USERNAME:QA_COORDINATOR_PASSWORD" \
  "teacher:QA_TEACHER_USERNAME:QA_TEACHER_PASSWORD" \
  "parent:QA_PARENT_USERNAME:QA_PARENT_PASSWORD" \
  "kiosk:QA_KIOSK_USERNAME:QA_KIOSK_PASSWORD" \
  "super_admin:QA_SUPER_ADMIN_USERNAME:QA_SUPER_ADMIN_PASSWORD"; do
  IFS=: read -r role username_key password_key <<< "$spec"
  response="$(login "$username_key" "$password_key")"
  token="$(printf '%s' "$response" | jq -er '.data.access_token // .data.token')"
  profile_code="$(status "$token" '/auth/profile')"

  if [[ "$role" == "kiosk" ]]; then
    qr_code="$(status "$token" '/attendance/staff/qr-token?refresh_nonce=role-smoke')"
    logs_code="$(status "$token" '/attendance/staff')"
    export_code="$(status "$token" '/attendance/staff/qr-logs/export')"
    [[ "$profile_code" == 200 && "$qr_code" == 200 && "$logs_code" == 200 && "$export_code" == 200 ]] || {
      echo "$role profile=$profile_code qr_token=$qr_code attendance_log=$logs_code qr_export=$export_code" >&2
      exit 1
    }
    echo "$role login=200 profile=$profile_code qr_token=$qr_code attendance_log=$logs_code qr_export=$export_code"
    continue
  fi

  dashboard_code="$(status "$token" "/dashboard/$role")"
  [[ "$profile_code" == 200 && "$dashboard_code" == 200 ]] || {
    echo "$role profile=$profile_code dashboard=$dashboard_code" >&2
    exit 1
  }
  echo "$role login=200 profile=$profile_code dashboard=$dashboard_code"
done
