-- Role-aware Help guides are structured so the app can show short guidance,
-- numbered workflow steps, and an action that opens the relevant feature.
alter table public.help_contents
  add column if not exists category text not null default 'General',
  add column if not exists workflow_steps jsonb not null default '[]'::jsonb,
  add column if not exists action_route text;

create unique index if not exists idx_help_contents_school_role_question
  on public.help_contents (school_id, role_name, question);

with guides(role_name, category, question, answer, workflow_steps, action_route) as (
  values
    ('teacher', 'Classroom & Attendance',
      'How do I mark daily student attendance for my class?',
      'Use Student Attendance only for a class or subject you are assigned to. Save the register after checking every learner.',
      jsonb_build_array('Open Student Attendance.', 'Choose the assigned class, section, date, and period when required.', 'Mark each student Present, Absent, Late, or the available status.', 'Review the total and save the register. A locked session must be corrected through the school process.'),
      '/teacher-attendance-screen'),
    ('teacher', 'Classroom & Attendance',
      'How do I view past attendance history for a student or class?',
      'Attendance History lets you review previously saved class registers. It does not create a new register.',
      jsonb_build_array('Open Attendance History.', 'Select the class or section and the date or period to review.', 'Use the student list and status summary to find the record.', 'Return to Student Attendance only when you need to mark an available session.'),
      '/teacher-attendance-history-screen'),
    ('teacher', 'Classroom & Attendance',
      'How do I check my own staff attendance record?',
      'My Attendance shows your own check-in and attendance log, not student attendance.',
      jsonb_build_array('Open My Attendance.', 'Check today''s status and check in if the action is available.', 'Use the attendance log to review earlier entries.', 'Report a missing or incorrect entry through the school''s support process.'),
      '/teacher-my-attendance-screen'),
    ('teacher', 'Leave Management',
      'How do I apply for casual, sick, or earned leave?',
      'Submit a leave request with the correct leave type, date range, and a clear reason before the leave date whenever possible.',
      jsonb_build_array('Open Leave.', 'Choose Request Leave.', 'Select the leave type and start and end dates.', 'Add the reason and submit. Do not submit overlapping requests.'),
      '/teacher-leave-screen'),
    ('teacher', 'Leave Management',
      'How do I track my leave requests and remaining leave balances?',
      'The Leave screen keeps your request history, approval status, and available balance together.',
      jsonb_build_array('Open Leave.', 'Review the Leave History section for Pending, Approved, or Rejected requests.', 'Open the Leave Balance section to see remaining entitlement.', 'Open a rejected request to read the school''s decision before applying again.'),
      '/teacher-leave-screen'),
    ('teacher', 'Homework & Grading',
      'How do I create and assign a new homework task to a class?',
      'Create homework from the Homework / Assignments screen so the class, subject, due date, and attachments stay linked.',
      jsonb_build_array('Open Homework / Assignments.', 'Choose the action to create homework.', 'Select only an assigned class and subject.', 'Add instructions, due date, and optional material, then publish.', 'Review the published card to confirm the correct class can see it.'),
      '/teacher-homework-screen'),
    ('teacher', 'Homework & Grading',
      'How do I review student homework submissions and download attachments?',
      'Open the homework item first, then use its submissions view to review only that assignment.',
      jsonb_build_array('Open Homework / Assignments.', 'Choose the homework item to review.', 'Open Submissions.', 'Open an attachment when provided and record feedback or completion through the available controls.'),
      '/teacher-homework-screen'),
    ('teacher', 'Lesson Planning & Documents',
      'How do I create and update my lesson planner?',
      'Lesson Planner is for plans connected to your assigned class and subject work.',
      jsonb_build_array('Open Lesson Planner.', 'Choose the relevant week, class, and subject.', 'Create a plan or open an existing plan to update it.', 'Save the learning objectives, activities, and attachments.', 'Review the saved status before leaving the screen.'),
      '/teacher-lesson-planner-screen'),
    ('teacher', 'Lesson Planning & Documents',
      'How do I share worksheets, notes, and study documents with students or parents?',
      'Use the teacher Documents area for class material and upload only files that are appropriate for the selected audience.',
      jsonb_build_array('Open Documents.', 'Choose upload or add document.', 'Select the intended class or audience when prompted.', 'Add a clear title and attach the file.', 'Confirm the item appears in the document list before telling families it is available.'),
      '/teacher-documents-screen'),
    ('teacher', 'Communication',
      'How do I start a chat message with a parent or colleague?',
      'Communication shows only the people and parent contacts available to your role and assigned classes.',
      jsonb_build_array('Open Communication.', 'Choose a parent contact or school-leadership conversation.', 'Start a new direct conversation when no thread exists.', 'Write a clear message and send.', 'Switch conversations from the list before replying to avoid sending to the wrong family.'),
      '/teacher-communication-screen'),
    ('teacher', 'Communication',
      'How do I create an announcement or event post and submit it for approval?',
      'Event posts are submitted for school review; publishing is not immediate until the required approval is complete.',
      jsonb_build_array('Open Event Posts.', 'Choose Create Post.', 'Add the title, message, audience, date, and approved media.', 'Submit the post for review.', 'Track its status and edit it if the reviewer requests changes.'),
      '/teacher-event-posts-screen'),
    ('teacher', 'Support',
      'How do I submit support tickets or report system issues?',
      'Use My Issues for a reproducible application problem or a request that needs school follow-up.',
      jsonb_build_array('Open My Issues.', 'Choose the option to create an issue.', 'Describe what you were doing, what you expected, and what happened.', 'Add a screenshot only if it does not expose student data unnecessarily.', 'Submit and check the issue status for updates.'),
      '/teacher-complaints-screen'),

    ('parent', 'Child Oversight',
      'How do I switch profiles if I have multiple children enrolled in the school?',
      'Use the child selector on the Parent Dashboard before opening attendance, homework, fees, or health details.',
      jsonb_build_array('Open the Parent Dashboard.', 'Use the child selector or child card.', 'Choose the child whose information you want to review.', 'Confirm the child name at the top of the next screen before taking any action.'),
      '/parent-dashboard-screen'),
    ('parent', 'Child Oversight',
      'How do I view my child''s daily and monthly attendance record?',
      'My Child Attendance shows attendance for the currently selected child.',
      jsonb_build_array('Select the correct child on the Parent Dashboard.', 'Open My Child Attendance.', 'Use the date or month controls to review the required period.', 'Check the status summary and contact the school if a record needs clarification.'),
      '/parent-attendance-screen'),
    ('parent', 'Child Oversight',
      'How do I update my child''s medical information and health records?',
      'Health updates should be accurate and limited to information the school needs to support your child.',
      jsonb_build_array('Select the correct child.', 'Open Health.', 'Review the existing health details.', 'Use the available update action to add or correct the record.', 'Save and confirm the updated information is displayed.'),
      '/parent-health-screen'),
    ('parent', 'Academic & Homework',
      'How do I view my child''s class timetable?',
      'The timetable is read-only for parents and follows the currently selected child.',
      jsonb_build_array('Select the correct child.', 'Open Class Timetable.', 'Choose the relevant day or week when controls are available.', 'Use the displayed subject, period, and time details to plan for the school day.'),
      '/parent-timetable-screen'),
    ('parent', 'Academic & Homework',
      'How do I check daily homework assignments?',
      'Homework & Assignments lists work issued to the selected child''s class.',
      jsonb_build_array('Select the correct child.', 'Open Homework & Assignments.', 'Choose the relevant homework card.', 'Read the instructions, due date, and teacher attachments before starting the work.'),
      '/parent-homework-screen'),
    ('parent', 'Academic & Homework',
      'How do I submit my child''s homework with photo or file attachments?',
      'Submit work from the homework item so the upload is attached to the correct assignment.',
      jsonb_build_array('Open Homework & Assignments and select the task.', 'Choose Submit Homework.', 'Add the response and attach the permitted photo or file.', 'Review the selected file and submit.', 'Confirm the submission status on the homework card.'),
      '/parent-homework-screen'),
    ('parent', 'Academic & Homework',
      'How do I review teacher comments on completed homework?',
      'Teacher feedback is shown within the completed homework item after the teacher has reviewed it.',
      jsonb_build_array('Open Homework & Assignments.', 'Choose the submitted or completed task.', 'Open the submission details.', 'Read the teacher feedback and any requested next step.'),
      '/parent-homework-screen'),
    ('parent', 'Fees & Payments',
      'How do I view pending fee invoices?',
      'The Fees screen shows the selected child''s invoices, due amounts, and payment status.',
      jsonb_build_array('Select the correct child.', 'Open Fees.', 'Review pending invoices and the due date.', 'Open an invoice for its amount and payment instructions before making an offline payment.'),
      '/parent-fees-screen'),
    ('parent', 'Fees & Payments',
      'How do I submit a payment request and upload an offline payment receipt or transaction proof?',
      'Use a payment request only after completing the school''s accepted offline payment method. Do not upload unrelated receipts.',
      jsonb_build_array('Open Fees and choose the relevant invoice.', 'Choose the payment request or proof-upload action.', 'Enter the payment reference and amount exactly as paid.', 'Attach a readable receipt or transaction proof.', 'Submit and wait for the school to review the request.'),
      '/parent-fees-screen/payment'),
    ('parent', 'Fees & Payments',
      'How do I download past fee receipts and check my payment history?',
      'Payment History contains completed payment records and available receipts for the selected child.',
      jsonb_build_array('Select the correct child.', 'Open Fees or Payment History.', 'Choose a completed payment.', 'Open or download the receipt when it is available.', 'Keep the receipt for your records.'),
      '/parent/payment-history'),
    ('parent', 'Leave & Meetings',
      'How do I book a meeting slot with my child''s class teacher?',
      'Book only an available PTM slot for the selected child and add a short topic so the teacher can prepare.',
      jsonb_build_array('Select the correct child.', 'Open PTM Booking.', 'Choose an available teacher and slot.', 'Add the meeting topic if requested.', 'Confirm the booking and check its status before visiting school.'),
      '/parent-ptm-booking-screen'),
    ('parent', 'Leave & Meetings',
      'How do I apply for student leave?',
      'A student leave request should include the selected child, date range, leave type when available, and a clear reason.',
      jsonb_build_array('Select the correct child.', 'Open Leave Requests.', 'Choose Request Leave.', 'Enter the dates and reason.', 'Submit and wait for school approval before treating the leave as confirmed.'),
      '/parent-leave-screen'),
    ('parent', 'Leave & Meetings',
      'How do I track the status of a student leave request?',
      'The Leave Requests screen displays your submitted request history and the school decision.',
      jsonb_build_array('Open Leave Requests.', 'Find the request in the history list.', 'Check whether it is Pending, Approved, or Rejected.', 'Open it for any reviewer note, then submit a new request only when necessary.'),
      '/parent-leave-screen'),
    ('parent', 'School Communication',
      'How do I chat with the class or subject teacher?',
      'Communication presents teacher contacts associated with your child; each child keeps separate teacher conversations.',
      jsonb_build_array('Select the correct child.', 'Open Communication.', 'Choose the class teacher, co-teacher, or school-leadership contact.', 'Open or start the direct conversation.', 'Send a concise message and check that the correct child context is shown.'),
      '/parent-teacher-chat-screen'),
    ('parent', 'School Communication',
      'How do I view school announcements, gallery photos, and the academic calendar?',
      'Announcements and school posts appear in the parent experience; calendar and gallery have their own screens.',
      jsonb_build_array('Open Academic Calendar to review dated school events.', 'Use the Parent Dashboard for current announcements and school posts.', 'Open the School Gallery from the shared navigation to view approved photos and media.'),
      '/parent-calendar-screen'),

    ('principal', 'Dashboard & School Setup',
      'How do I review the school configuration and general details?',
      'School Profile holds the school-level information used across the portal. Review changes carefully before saving.',
      jsonb_build_array('Open School Profile.', 'Review the current general details.', 'Choose Edit for the section you need to change.', 'Save and reopen the section to confirm the data was retained.'),
      '/principal-school-profile-screen'),
    ('principal', 'Dashboard & School Setup',
      'How do I configure or transition to a new Academic Year?',
      'Academic Management is the starting point for academic years, subjects, classes, sections, and related setup.',
      jsonb_build_array('Open Academic Management.', 'Open Academic Years.', 'Create or update the year and its dates.', 'Set the intended active year only after verifying the new setup.', 'Complete classes, sections, subjects, and timetable preparation before staff begin using the year.'),
      '/academic-management-screen'),
    ('principal', 'Dashboard & School Setup',
      'How do I set up new classrooms and sections in the Class Hub?',
      'Class Hub manages class-level setup and should be completed before assigning teachers or marking attendance.',
      jsonb_build_array('Open Class Hub.', 'Create or select the class.', 'Add the required sections.', 'Assign class-teacher or co-teacher details where available.', 'Review the class card before enrolling or assigning students.'),
      '/principal-classes-screen'),
    ('principal', 'User Management & Access Control',
      'How do I create accounts for new staff, parents, or students?',
      'Create accounts through User Management and follow the role-specific form so the account is linked to the right person.',
      jsonb_build_array('Open User Management.', 'Choose Create Account.', 'Select the intended role.', 'Enter the verified identity and contact information.', 'Save and confirm the new account appears in the relevant role list.'),
      '/principal-user-management-screen'),
    ('principal', 'User Management & Access Control',
      'How do I edit permissions or reset credentials for a user?',
      'Use the existing user record so changes remain linked to the correct account.',
      jsonb_build_array('Open User Management.', 'Find the user by role or search.', 'Open Edit Account or the credential action.', 'Apply only the required changes.', 'Save and confirm the user can use the updated account through the normal sign-in flow.'),
      '/principal-user-management-screen'),
    ('principal', 'User Management & Access Control',
      'How do I assign parents or guardians to their respective children?',
      'Parent-child assignments control which child data and teacher contacts a parent can access.',
      jsonb_build_array('Open Assign Children.', 'Find the parent account.', 'Select the correct enrolled child or children.', 'Save the assignment.', 'Ask the parent to reopen their portal and confirm the correct child profile is visible.'),
      '/principal-user-management-screen/assign-children'),
    ('principal', 'Finance & Fees',
      'How do I create a new fee structure for a class?',
      'Create fee rules before generating invoices. Confirm class, academic year, frequency, and amount before saving.',
      jsonb_build_array('Open Fees.', 'Choose Fee Structures.', 'Create the fee structure and select the intended class or section.', 'Add the amount, frequency, and applicable period.', 'Save and review the structure before generating invoices.'),
      '/fee-home-screen'),
    ('principal', 'Finance & Fees',
      'How do I generate monthly invoices for students?',
      'Invoice generation should happen only after fee structures and the active academic context are correct.',
      jsonb_build_array('Open Fees.', 'Choose the invoice generation action.', 'Select the class, billing month, and eligible students.', 'Review the invoice preview and totals.', 'Generate the invoices and verify they appear in the student ledger.'),
      '/principal/fees'),
    ('principal', 'Finance & Fees',
      'How do I record offline fee payments?',
      'Record an offline payment against the correct student and invoice, using the school''s verified payment reference.',
      jsonb_build_array('Open Fees.', 'Find the student or invoice.', 'Choose Record Payment.', 'Enter the amount, date, method, and reference.', 'Save and verify the ledger balance and receipt details.'),
      '/principal/fees'),
    ('principal', 'Finance & Fees',
      'How do I review and approve pending parent payment requests?',
      'Payment proof approval should match the submitted amount, reference, and the school''s actual payment record.',
      jsonb_build_array('Open Payment Requests.', 'Open a pending request.', 'Review the receipt or transaction proof and invoice details.', 'Approve or reject with the appropriate decision.', 'Confirm the parent-facing payment status and ledger are updated.'),
      '/principal-fees-screen/payment-requests'),
    ('principal', 'Finance & Fees',
      'How do I check class-wise or student-wise fee ledgers?',
      'The fee ledger is the source for invoice, payment, and balance review.',
      jsonb_build_array('Open Fees.', 'Choose Fee Ledger.', 'Filter by class or search for a student.', 'Open the ledger row to review invoices, receipts, paid amounts, and balance.', 'Export or follow up only after checking the selected academic period.'),
      '/fee-ledger-screen'),
    ('principal', 'Academic Oversight',
      'How do I manage subjects and map them to classes?',
      'Academic Management contains subject setup and class-wise subject mapping.',
      jsonb_build_array('Open Academic Management.', 'Open Subjects to create or update a subject.', 'Open the class or subject mapping area.', 'Assign the subject to the intended class or section.', 'Save and confirm the subject is visible in the class setup.'),
      '/academic-management-screen'),
    ('principal', 'Academic Oversight',
      'How do I assign subject teachers to specific sections?',
      'Teacher assignment should be made only after the staff profile, subject, and target section exist.',
      jsonb_build_array('Open Academic Management or Class Hub.', 'Choose the relevant class or subject mapping.', 'Select the staff member and the section.', 'Save the assignment.', 'Confirm the teacher sees the correct class and subject in their portal.'),
      '/academic-management-screen'),
    ('principal', 'Academic Oversight',
      'How do I create and manage class timetables?',
      'Timetable management uses class and subject assignments, so complete them before publishing a schedule.',
      jsonb_build_array('Open Timetable.', 'Select the academic year, class, and section.', 'Add or edit period rows with subject, teacher, and time.', 'Check for overlapping times before saving.', 'Review the timetable as a teacher or parent would see it.'),
      '/principal-timetable-screen'),
    ('principal', 'Academic Oversight',
      'How do I monitor teacher lesson planners?',
      'Lesson Planners gives school leadership class-wise visibility of teacher planning and attachments.',
      jsonb_build_array('Open Lesson Planners.', 'Filter by class, teacher, or date when required.', 'Open a planner to review objectives and uploaded material.', 'Use the available review or follow-up process for incomplete plans.'),
      '/principal-lesson-planner-screen'),
    ('principal', 'Approvals & Oversight',
      'How do I review and approve student and staff leave applications?',
      'Approval Center combines operational requests. Review dates, role, and supporting context before deciding.',
      jsonb_build_array('Open Approval Center.', 'Filter to leave requests.', 'Open the request and verify the dates and reason.', 'Approve or reject with a clear note where the action asks for one.', 'Confirm the request moves out of Pending.'),
      '/approval-center-screen'),
    ('principal', 'Approvals & Oversight',
      'How do I approve event notices and school announcements?',
      'Review the audience, dates, wording, and media before approving a post for school families.',
      jsonb_build_array('Open Event Approvals.', 'Open the pending event or announcement.', 'Review title, content, audience, schedule, and media.', 'Approve, reject, or request an edit using the available workflow.', 'Confirm the final status before expecting it to appear in the school feed.'),
      '/principal-event-approvals-screen'),
    ('principal', 'Approvals & Oversight',
      'How do I review daily attendance metrics?',
      'Principal Attendance combines staff, student, class, monitoring, and reporting views.',
      jsonb_build_array('Open Principal Attendance.', 'Choose the date and attendance view.', 'Review staff check-in, student, and class metrics.', 'Open a class or student detail when a record needs follow-up.', 'Use refresh after making related attendance changes.'),
      '/principal-attendance-screen'),
    ('principal', 'Approvals & Oversight',
      'How do I access school-wide audit logs?',
      'Audit Logs is for reviewing recorded operational activity; use filters to narrow the review.',
      jsonb_build_array('Open Audit Logs.', 'Set the date range or available filters.', 'Review the action, actor, module, and timestamp.', 'Open related context where available before escalating an issue.'),
      '/principal-audit-logs-screen'),

    ('coordinator', 'Coordinator Access',
      'What can I do as a Coordinator?',
      'Coordinator uses the school-leadership workflows for academics, people, attendance, approvals, communication, and audit visibility. Finance and fee workflows are intentionally excluded.',
      jsonb_build_array('Open the Coordinator Dashboard.', 'Use the same leadership navigation for operational work.', 'Use Help to open the correct academic, approval, communication, or attendance workflow.', 'Contact the Principal for fee structures, invoices, payment requests, and ledgers.'),
      '/coordinator-dashboard-screen'),
    ('coordinator', 'Dashboard & School Setup',
      'How do I configure or transition to a new Academic Year?',
      'Use Academic Management for academic year setup; fee exports and finance configuration remain principal-only.',
      jsonb_build_array('Open Academic Management.', 'Open Academic Years.', 'Create or update the dates and active-year setup.', 'Complete classes, sections, subjects, and timetable preparation before staff begin using the year.'),
      '/academic-management-screen'),
    ('coordinator', 'Dashboard & School Setup',
      'How do I set up new classrooms and sections in the Class Hub?',
      'Class Hub manages operational class and section setup.',
      jsonb_build_array('Open Class Hub.', 'Create or select the class.', 'Add the required sections.', 'Assign class-teacher or co-teacher details where available.', 'Review the class card before assigning students.'),
      '/principal-classes-screen'),
    ('coordinator', 'User Management & Access Control',
      'How do I create or update staff, parent, and student accounts?',
      'Use User Management for operational account creation and updates. Do not change finance-related access or fee records.',
      jsonb_build_array('Open User Management.', 'Find the person or choose Create Account.', 'Select the correct role and complete the required details.', 'Save and confirm the account appears in its role list.'),
      '/principal-user-management-screen'),
    ('coordinator', 'User Management & Access Control',
      'How do I assign parents or guardians to their respective children?',
      'Parent-child assignments control the parent''s child visibility and communication scope.',
      jsonb_build_array('Open Assign Children.', 'Find the parent account.', 'Select the correct child or children.', 'Save the assignment.', 'Ask the parent to reopen the portal and confirm the correct child profile is visible.'),
      '/principal-user-management-screen/assign-children'),
    ('coordinator', 'Academic Oversight',
      'How do I manage subjects and assign teachers to sections?',
      'Academic Management and Class Hub contain the non-finance setup for subjects, classes, and teacher assignments.',
      jsonb_build_array('Open Academic Management.', 'Create or update the subject.', 'Open the class or subject mapping area.', 'Assign the subject and teacher to the intended section.', 'Save and confirm the teacher sees the assigned class or subject.'),
      '/academic-management-screen'),
    ('coordinator', 'Academic Oversight',
      'How do I create and manage class timetables?',
      'Timetable management depends on existing classes, subjects, and teacher assignments.',
      jsonb_build_array('Open Timetable.', 'Select the academic year, class, and section.', 'Add or edit period rows with subject, teacher, and time.', 'Check for overlaps before saving.', 'Review the timetable from the class perspective.'),
      '/principal-timetable-screen'),
    ('coordinator', 'Academic Oversight',
      'How do I monitor teacher lesson planners?',
      'Lesson Planners provides class-wise oversight of teacher plans and material.',
      jsonb_build_array('Open Lesson Planners.', 'Filter by class, teacher, or date.', 'Open a planner to review objectives and material.', 'Follow up through the available school workflow when information is incomplete.'),
      '/principal-lesson-planner-screen'),
    ('coordinator', 'Approvals & Oversight',
      'How do I review student and staff leave applications?',
      'Use Approval Center for operational leave review, checking dates and reason before making a decision.',
      jsonb_build_array('Open Approval Center.', 'Filter to leave requests.', 'Open the request and verify dates and reason.', 'Approve or reject with a clear note when requested.', 'Confirm the request no longer shows as Pending.'),
      '/approval-center-screen'),
    ('coordinator', 'Approvals & Oversight',
      'How do I approve event notices and school announcements?',
      'Event approval is available to school leadership; review the audience, dates, and media before deciding.',
      jsonb_build_array('Open Event Approvals.', 'Open the pending item.', 'Review its audience, timing, wording, and media.', 'Approve, reject, or request an edit.', 'Confirm its final status.'),
      '/principal-event-approvals-screen'),
    ('coordinator', 'Approvals & Oversight',
      'How do I review daily attendance metrics?',
      'Principal Attendance is shared with Coordinator for operational attendance oversight.',
      jsonb_build_array('Open Principal Attendance.', 'Choose the date and view.', 'Review staff, student, and class metrics.', 'Open a detail when a record requires follow-up.', 'Use refresh after related attendance activity.'),
      '/principal-attendance-screen'),
    ('coordinator', 'Communication',
      'How do I message teachers or parents from the Coordinator portal?',
      'Communication provides leadership-scoped teacher and parent contacts. Direct replies stay owned by the coordinator who started the conversation.',
      jsonb_build_array('Open Messages.', 'Choose Teachers or Parents and apply the class filter if needed.', 'Select a contact or existing conversation.', 'Start a direct conversation and send the message.', 'Use Monitor for read-only oversight of parent-teacher conversations.'),
      '/principal-chat-communications-screen'),
    ('coordinator', 'Approvals & Oversight',
      'How do I access school-wide audit logs?',
      'Audit Logs provides recorded operational activity for investigation and follow-up.',
      jsonb_build_array('Open Audit Logs.', 'Set the available date or activity filters.', 'Review the actor, action, module, and timestamp.', 'Open related context where available before escalating an issue.'),
      '/principal-audit-logs-screen')
)
insert into public.help_contents (
  school_id,
  role_name,
  category,
  question,
  answer,
  workflow_steps,
  action_route
)
select
  schools.id,
  guides.role_name,
  guides.category,
  guides.question,
  guides.answer,
  guides.workflow_steps,
  guides.action_route
from public.schools as schools
cross join guides
on conflict (school_id, role_name, question) do nothing;
